# -*- coding: utf-8 -*-
"""File1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y55OxXozOdkhYyRJqw6zngaY-ToMwV7R
"""

import io
from google.colab import files
uploaded=files.upload()

#load libraries
import numpy as np         
import pandas as pd      
data = pd.read_csv('data.csv', index_col=False,)

data.drop('id', axis =1, inplace=True)
data.head(2)

"""Checking the data, the no. of cells and the properties that the data possess."""

data.head(2)

"""Using the shape command"""

data.shape

"""From we got the no. of cells and the no. of properties that the data possess.

Information for the properties and the non-null objects is given.
"""





data.info()

"""Allocation of the variables for maligant and benign."""

data.diagnosis.unique()

