# -*- coding: utf-8 -*-
"""File2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14_XuqTDim-uc5hb9fV8lfpKKF1UnOboR

Load the data
"""

import io
from google.colab import files
uploaded=files.upload()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt

#Load libraries for data processing
import pandas as pd
import numpy as np
from scipy.stats import norm
import seaborn as sns # visualization


plt.rcParams['figure.figsize'] = (15,8) 
plt.rcParams['axes.titlesize'] = 'large'

data = pd.read_csv('clean-data.csv', index_col=False)
data.drop('Unnamed: 0',axis=1, inplace=True)
#data.head(2)

data.describe()

data.skew()

"""The skew result show a positive (right) or negative (left) skew. We can see that radius_mean, perimeter_mean, area_mean, concavity_mean and concave_points_mean are useful in predicting cancer type due to the distinct grouping between malignant and benign cancer types in these features."""

data.diagnosis.unique()

# Group by diagnosis and review the output.
diag_gr = data.groupby('diagnosis', axis=0)
pd.DataFrame(diag_gr.size(), columns=['of observations'])

"""Observation : We got 357 belign and 212 maligant cells from the commands we have used above."""